In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [ ]:
# @title Default title text
## Introduction to tensors
# Tensor are a way to represent data
#  torch.Tensor : A multi deminsional matrix containing elements of a single data type
# First is a scalar

In [ ]:
# Scalar, has no demensions
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# The number of dimensions the scalar tensor has
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
# Number of square backets denote the dimensions there are
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR_TEST_DIM = torch.tensor([[[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9],
                                [10, 11, 12]]])
TENSOR_TEST_DIM

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
  TENSOR_TEST_DIM.ndim

3

In [ ]:
TENSOR_TEST_DIM.shape

torch.Size([1, 4, 3])

## Random Tensors
# Why random tensors?
# Random tensors are important because the way nueral netwroks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
~Start with random numbers -> look at data -> update random numbers -> loook at data -> update random numbers

In [ ]:
# Create a random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1899, 0.5739, 0.0347, 0.2093],
        [0.1612, 0.5188, 0.0100, 0.7197],
        [0.8592, 0.0644, 0.1472, 0.2462]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
RANDOM_TENSOR_TEST = torch.rand(size=(2, 5, 6))
RANDOM_TENSOR_TEST

tensor([[[0.8472, 0.1701, 0.7308, 0.9008, 0.3392, 0.7048],
         [0.8721, 0.5301, 0.5147, 0.5564, 0.9810, 0.5972],
         [0.7595, 0.3254, 0.7045, 0.1322, 0.2931, 0.3159],
         [0.4503, 0.5660, 0.5134, 0.5160, 0.6926, 0.3191],
         [0.7428, 0.0545, 0.9103, 0.3230, 0.2866, 0.5318]],

        [[0.2229, 0.5759, 0.0299, 0.9432, 0.8060, 0.1637],
         [0.3936, 0.6860, 0.3311, 0.9569, 0.9812, 0.3892],
         [0.8244, 0.0029, 0.5335, 0.1735, 0.0916, 0.4933],
         [0.9310, 0.0353, 0.6708, 0.0313, 0.4694, 0.4938],
         [0.0232, 0.8790, 0.6500, 0.1537, 0.6650, 0.6645]]])

In [ ]:
# Create a tensor filled with zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 # Create a tensor of all ones
 ones = torch.ones(3, 4)
 ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# Using torch.range()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
_77_jump = torch.arange(start=0, end=1000, step=77)
_77_jump

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What data type is the tensor, eg. float 32 or float 16
                               device=None, #  What device your tensor is on
                               requires_grad=False) # Wether or not to track gradients with tensor operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
product = float_16_tensor * float_32_tensor
product, product.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [ ]:
some_tensor = torch.rand([2, 3, 5],
                         dtype=torch.float16,
                         device='cuda')

In [ ]:
print(f"The tensor data type is: {some_tensor.dtype}")
print(f"The tensor shape is: {some_tensor.shape}")
print(f"The device tensor is on: {some_tensor.device}")

The tensor data type is: torch.float16
The tensor shape is: torch.Size([2, 3, 5])
The device tensor is on: cuda:0


# Manipulating tensors, tensor operations
Tensor operations
- Addition
- Subtraction
- Multiplication (In terms of elements)
- Division
- Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# Matrix multiplication with forloop
value = 0
for i in range(len(tensor)):
  value  += tensor[i] * tensor[i]
print(value)

tensor(14)


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
print(f"Shape of A is:{tensor_A.shape}\n Shape of B is:{tensor_B.shape}")

Shape of A is:torch.Size([3, 2])
 Shape of B is:torch.Size([3, 2])


In [ ]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
# Transposing A instead of B give a different output and causes the outter dimesons to be 2
# When we transpose A the inner numbers match, 3 and the outcome is equal to the outer, 2.
# This is a different tensor shape and values from A normal with B.T than A.T with B normal
print(f"Tensor_A: {tensor_A.shape} | Tensor_B: {tensor_B.T.shape}")
print("-------------------------------------------------------------")
print(f"Tensor_A: {tensor_A.T.shape} | Tensor_B: {tensor_B.shape}")

Tensor_A: torch.Size([3, 2]) | Tensor_B: torch.Size([2, 3])
-------------------------------------------------------------
Tensor_A: torch.Size([2, 3]) | Tensor_B: torch.Size([3, 2])


In [ ]:
# Aggregrate functions
x = torch.arange(start=0, end=110, step=10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
x.max(), torch.max(x)

(tensor(100), tensor(100))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [ ]:
x.sum(), torch.sum(x)

(tensor(550), tensor(550))

In [ ]:
print(f"The position of the min in the tensor is: {torch.argmin(x)}")
print(f"The position of the max in the tensor is: {torch.argmax(x)}")

The position of the min in the tensor is: 0
The position of the max in the tensor is: 10


In [ ]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view of y. A view of a tensor shares the same memory address. Chaning z would change the tensor of y
z = y.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=1)
y_stacked, y_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked, y_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
squeeze_x = torch.zeros(2, 1, 2, 1, 2)
squeeze_x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
squeezed_x = torch.squeeze(squeeze_x)
squeezed_x.size()

torch.Size([2, 2, 2])

In [ ]:
index_image = torch.rand(size=(224, 224, 3))
index_image

tensor([[[0.2981, 0.5631, 0.4721],
         [0.2406, 0.9986, 0.3054],
         [0.8526, 0.4576, 0.3552],
         ...,
         [0.3552, 0.7273, 0.9600],
         [0.9494, 0.0115, 0.7147],
         [0.3219, 0.5787, 0.6726]],

        [[0.3624, 0.6888, 0.3335],
         [0.0615, 0.7390, 0.3819],
         [0.9777, 0.0067, 0.4874],
         ...,
         [0.7229, 0.6932, 0.7694],
         [0.0117, 0.7521, 0.9069],
         [0.1893, 0.0986, 0.1602]],

        [[0.7309, 0.4537, 0.4252],
         [0.8974, 0.4559, 0.4129],
         [0.9677, 0.4351, 0.9869],
         ...,
         [0.4484, 0.3838, 0.7341],
         [0.6141, 0.6249, 0.1399],
         [0.5944, 0.3142, 0.3376]],

        ...,

        [[0.6992, 0.6540, 0.8404],
         [0.4620, 0.5146, 0.9857],
         [0.9484, 0.4954, 0.2255],
         ...,
         [0.2926, 0.2480, 0.0837],
         [0.7090, 0.6962, 0.0108],
         [0.2221, 0.1351, 0.3254]],

        [[0.7950, 0.2376, 0.4285],
         [0.8410, 0.0819, 0.6929],
         [0.

In [ ]:
index_image[2, 1, 1]
index_image.ndim

3

In [ ]:
index_prac = torch.arange(1, 10).reshape(1, 3, 3)
index_prac

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
index_prac[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
index_prac[0][0]

tensor([1, 2, 3])

In [ ]:
index_prac[0][0][0]

tensor(1)

In [ ]:
index_prac[1][1][1] # Out of bounds because it is at one dimension. So it is only 0

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
index_prac[0, 2, 2]

tensor(9)

In [ ]:
# You can use ":" to select "all" of target dimesion
index_prac[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dimesions but only index 1 of 2nd dimension
index_prac[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
index_prac[:, 1, 1]

tensor([5])

In [ ]:
# Get index of 0 and 0th and 1st dimension and all values of 2nd dimension
index_prac[0, 0, :]

tensor([1, 2, 3])

In [ ]:
index_prac

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
index_prac[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
#Pytorch tensors and NumPy
# NumPy is a popular scientific python numerical computing libary.
# And because of this PyTorch has functionality to interact with it.
# Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
# pytorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: When converting from numpy -> to pytorch, pytorch will refelect numpy default data type of float64, rather than pytorch float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumpPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (Trying to take the random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again ....`

To reduce the randomness in neural networks and pytorch comes the concept of a **Random Seed**.

What the random seed does is "flavour" the randomness



In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6646, 0.0095, 0.1617, 0.7704],
        [0.2622, 0.3139, 0.5214, 0.4670],
        [0.2014, 0.6938, 0.4833, 0.6679]])
tensor([[0.2775, 0.5553, 0.6816, 0.3130],
        [0.8892, 0.6005, 0.8296, 0.1321],
        [0.3750, 0.9216, 0.0812, 0.8046]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
# Setting random seed
random_seed = 101
torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

# If you use the torch manual seed, it generally only works for one block of random code. Will need to call it before every use, need to reset the random seed

tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716]])
tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## Running tensors and PyTorch objects on the GPUs (and making faster computations)
# Gpus = faster computation on numbers, thanks to CUDA and NIVIDA + Pytorch.

# Use google co-labs
# Use your own
# Using Cloud : GCP, AWS, Azure

# For 2, and 3 pytorch + GPU Drivers (CUDA) takes a little bit of setting up



In [ ]:
# Check for GPU Access with pytorch
torch.cuda.is_available()

True

In [ ]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
torch.cpu.device_count()

1

In [ ]:
## Putting tensors and models on the gpu
# Putting the tensors/models on the GPU because GPU is faster computations

In [ ]:
# Create a tensor (deafault on the cpu)
tensor = torch.tensor([1, 2, 3], device='cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to gpu if avaliable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#### 4. Moving tensors back to the CPU, since numpy works on the CPU
# If tensor on GPU cant transform it to NumPy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Pytorch excersies and Cirriculum